[build-system]
requires = ["setuptools >= 61.0"]

[project]
name = "Apophis"
version = "0.0.1"

[tools.setuptools]
py-modules = ["Apophis_Class","Plotting"]

dependencies = [
    "numpy", "astropy", "matplotlib"
]
